### ISSUE TITLE
Slow / stuttering output

### ISSUE THREAD

**Issue by paines** [AndrewFromMelbourne/raspi2fb#1]
First of all, thanks for this little project. It helped me a lot to get things running with my USB Display and Rpi2. I tested the combination of both with a video played via omxplayer and also the game Descent2(d2x-rebirth). Unfortunatley the copy of the framebuffer is stuttering. My USB Display uses a resultion of 1366x768 or 1360x768. I guess the amount of pixels is just to much to be handled on the fly. A diffrent approach would be to use a lower resolution on the hdmi side, e.g. 480p and then scale it up to 1360. What do youor others who use this tool think about that ? Also it would be interesting to me, what kind of resultion on both sides, HDMI and FB0 you are using. Thanks!

**Comment by AndrewFromMelbourne** [comment]
Hi. I am glad you find this useful. I don't actually use it myself. I wrote it in response to a question about how to speed up the original [fbcp program](https://github.com/tasanakorn/rpi-fbcp). The optimization applied is to ensure only pixels that have changed are written to the display. This is great for reasonably static displays like the desktop, but doesn't help for dynamic output such as video games and videos.

You can actually do what you are suggesting by forcing the Raspberry Pi HDMI output to a specific resolution. I use the following in my config.txt file to force my Raspberry Pi to the same resolution as my TFT/SPI display.

```
# custom mode to match LCD
hdmi_force_hotplug=1
hdmi_cvt=480 320 60
hdmi_group=2
hdmi_mode=87
```

However, I don't think this will solve your issue. The bandwidth to the USB display is limited and I would think this is the limiting factor. Reducing the HDMI resolution won't reduce the amount of data being pushed over the USB interface to your display.

When I tested this program, I have both HDMI set to 480x320. This is the same as FB1. The framebuffer on the Raspberry Pi (FB0) isn't used at all by this program.

**Comment by paines** [comment]
Thanks for your answer. I really appreciate it. I just googled a bit and found out that USB2  has a bandwidth of 480 Mbit/s or 60 MB/s. If we have want to handle full HD on then HDMI with 1920x1080 in 32 bit, this would result in 7.9 MB/s, lets round up to 8 MB/s.  If we only can handle  60MB/s then we have 60/8 which result in 7.5 frames.... which is way to little, cause for a fluid motion we want at least 24 fps. Also the 60MB/s is a theoretical value. So peeps, keep in mind: do your maths before purchasing ;)
Lowering the resultion on HD doesn't help much, cause we would then only render a part of the display. 
Follow up: 
Same calculation reveals: if we keep both resultions to 1366x768 like in my case, it comes down to 25fps (theoretically), of course only in 16 bit per pixel.
