### ISSUE TITLE
Use pkgconfig for better integration in Yocto

### ISSUE THREAD

**Issue by jgueytat** [AndrewFromMelbourne/raspi2fb#2]
Hi,

I was following tasanakorn where I first picked the code.
I just proposed a pull request for a better integration in Yocto. The point is only to remove the hard linking thanks to pkgconfig.

Do you know if your repository is the main one? at least for Raspbian? I'll propose you a pull request in case.

Thanks in advance!
Have a good day,
Julien

**Comment by AndrewFromMelbourne** [comment]
Hi Julien, I am the author of the code. There may be other forks around, but I would expect mine is the main repository. I am always happy to look at pull requests,

Thanks,

Andrew

**Comment by jgueytat** [comment]
Great news! :)
I need to push some patch for qtbase and psplash first.
I'm modifying psplash so that you can select another frambuffer.
The point is to get fb1 used for the framebuffer. Then the application and the copy from fb0 to fb1.

Which Splash Screen software do you use? I might propose the correction there too.

-Julien

**Comment by AndrewFromMelbourne** [comment]
I don't use any splash screen software. I am not sure that I understand. This software simply copies from the Raspberry Pi's native display to a framebuffer.

**Comment by jgueytat** [comment]
Yep!
The point was to have a full startup on the PiTFT including Psplash. If you launch Psplash on fb1 It will appear sooner than on fb0 with the copy.

**Comment by jgueytat** [comment]
https://github.com/AndrewFromMelbourne/raspi2fb/pull/3

I was not able to test it on Raspbian but that should be ok.
Best Regards,
